version: "3.8"

services:
  db:
    image: mariadb
    env_file: .env
    volumes:
      - ./output/prod-db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MARIADB_DATABASE: $DB_DATABASE
    ports:
      - "${DB_PORT}:3306"
    

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${API_PORT}:80"
    env_file: .env
    image: ghcr.io/vincent-lauwen/user-service:latest
    environment:
      - DBHOST=db

