apiVersion: v1
kind: Service
metadata:
    name: "kwetterk8s-userservice"
    labels:
        app: "kwetterk8s-userservice"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kwetterk8s-userservice"
