on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kwettercr.azurecr.io
        username: ${{ secrets.acr_kwettercr_username }}
        password: ${{ secrets.acr_kwettercr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kwettercr.azurecr.io/kwetterk8s:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push kwettercr.azurecr.io/kwetterk8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kwetterk8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep user-service-k8safc5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace user-service-k8safc5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: user-service-k8safc5
        container-registry-url: kwettercr.azurecr.io
        container-registry-username: ${{ secrets.acr_kwettercr_username }}
        container-registry-password: ${{ secrets.acr_kwettercr_password }}
        secret-name: kwetterk8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: user-service-k8safc5
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          kwettercr.azurecr.io/kwetterk8s:${{ github.sha }}
        imagepullsecrets: |
          kwetterk8sdockerauth
